package com.example.hexagonalchess.domain_layer

fun getTileIndex(tileId: TileId, boardType: BoardType): Int {
    return when(boardType) {
        BoardType.DEFAULT -> when(tileId) {
            TileId.A1 -> 7
            TileId.A2 -> 6
            TileId.A3 -> 5
            TileId.A4 -> 4
            TileId.A5 -> 3
            TileId.A6 -> 2
            TileId.A7 -> 1
            TileId.A8 -> 0
            TileId.B1 -> 16
            TileId.B2 -> 15
            TileId.B3 -> 14
            TileId.B4 -> 13
            TileId.B5 -> 12
            TileId.B6 -> 11
            TileId.B7 -> 10
            TileId.B8 -> 9
            TileId.B9 -> 8
            TileId.C1 -> 26
            TileId.C2 -> 25
            TileId.C3 -> 24
            TileId.C4 -> 23
            TileId.C5 -> 22
            TileId.C6 -> 21
            TileId.C7 -> 20
            TileId.C8 -> 19
            TileId.C9 -> 18
            TileId.C10 -> 17
            TileId.D1 -> 37
            TileId.D2 -> 36
            TileId.D3 -> 35
            TileId.D4 -> 34
            TileId.D5 -> 33
            TileId.D6 -> 32
            TileId.D7 -> 31
            TileId.D8 -> 30
            TileId.D9 -> 29
            TileId.D10 -> 28
            TileId.D11 -> 27
            TileId.E1 -> 49
            TileId.E2 -> 48
            TileId.E3 -> 47
            TileId.E4 -> 46
            TileId.E5 -> 45
            TileId.E6 -> 44
            TileId.E7 -> 43
            TileId.E8 -> 42
            TileId.E9 -> 41
            TileId.E10 -> 40
            TileId.E11 -> 39
            TileId.E12 -> 38
            TileId.F1 -> 60
            TileId.F2 -> 59
            TileId.F3 -> 58
            TileId.F4 -> 57
            TileId.F5 -> 56
            TileId.F6 -> 55
            TileId.F7 -> 54
            TileId.F8 -> 53
            TileId.F9 -> 52
            TileId.F10 -> 51
            TileId.F11 -> 50
            TileId.G1 -> 70
            TileId.G2 -> 69
            TileId.G3 -> 68
            TileId.G4 -> 67
            TileId.G5 -> 66
            TileId.G6 -> 65
            TileId.G7 -> 64
            TileId.G8 -> 63
            TileId.G9 -> 62
            TileId.G10 -> 61
            TileId.H1 -> 79
            TileId.H2 -> 78
            TileId.H3 -> 77
            TileId.H4 -> 76
            TileId.H5 -> 75
            TileId.H6 -> 74
            TileId.H7 -> 73
            TileId.H8 -> 72
            TileId.H9 -> 71
            TileId.I1 -> 87
            TileId.I2 -> 86
            TileId.I3 -> 85
            TileId.I4 -> 84
            TileId.I5 -> 83
            TileId.I6 -> 82
            TileId.I7 -> 81
            TileId.I8 -> 80
            else -> -1
        }
        BoardType.STAR_CHESS -> when(tileId) {
            TileId.A1 -> 0
            TileId.B1 -> 2
            TileId.B2 -> 1
            TileId.C1 -> 9
            TileId.C2 -> 8
            TileId.C3 -> 7
            TileId.C4 -> 6
            TileId.C5 -> 5
            TileId.C6 -> 4
            TileId.C7 -> 3
            TileId.D1 -> 15
            TileId.D2 -> 14
            TileId.D3 -> 13
            TileId.D4 -> 12
            TileId.D5 -> 11
            TileId.D6 -> 10
            TileId.E1 -> 20
            TileId.E2 -> 19
            TileId.E3 -> 18
            TileId.E4 -> 17
            TileId.E5 -> 16
            TileId.F1 -> 26
            TileId.F2 -> 25
            TileId.F3 -> 24
            TileId.F4 -> 23
            TileId.F5 -> 22
            TileId.F6 -> 21
            TileId.G1 -> 33
            TileId.G2 -> 32
            TileId.G3 -> 31
            TileId.G4 -> 30
            TileId.G5 -> 29
            TileId.G6 -> 28
            TileId.G7 -> 27
            TileId.H1 -> 35
            TileId.H2 -> 34
            TileId.I1 -> 36
            else -> -1
        }

        BoardType.SHAFRAN -> when(tileId) {
            TileId.A1 -> 5
            TileId.A2 -> 4
            TileId.A3 -> 3
            TileId.A4 -> 2
            TileId.A5 -> 1
            TileId.A6 -> 0
            TileId.B1 -> 12
            TileId.B2 -> 11
            TileId.B3 -> 10
            TileId.B4 -> 9
            TileId.B5 -> 8
            TileId.B6 -> 7
            TileId.B7 -> 6
            TileId.C1 -> 20
            TileId.C2 -> 19
            TileId.C3 -> 18
            TileId.C4 -> 17
            TileId.C5 -> 16
            TileId.C6 -> 15
            TileId.C7 -> 14
            TileId.C8 -> 13
            TileId.D1 -> 29
            TileId.D2 -> 28
            TileId.D3 -> 27
            TileId.D4 -> 26
            TileId.D5 -> 25
            TileId.D6 -> 24
            TileId.D7 -> 23
            TileId.D8 -> 22
            TileId.D9 -> 21
            TileId.E1 -> 39
            TileId.E2 -> 38
            TileId.E3 -> 37
            TileId.E4 -> 36
            TileId.E5 -> 35
            TileId.E6 -> 34
            TileId.E7 -> 33
            TileId.E8 -> 32
            TileId.E9 -> 31
            TileId.E10 -> 30
            TileId.F1 -> 48
            TileId.F2 -> 47
            TileId.F3 -> 46
            TileId.F4 -> 45
            TileId.F5 -> 44
            TileId.F6 -> 43
            TileId.F7 -> 42
            TileId.F8 -> 41
            TileId.F9 -> 40
            TileId.G1 -> 56
            TileId.G2 -> 55
            TileId.G3 -> 54
            TileId.G4 -> 53
            TileId.G5 -> 52
            TileId.G6 -> 51
            TileId.G7 -> 50
            TileId.G8 -> 49
            TileId.H1 -> 63
            TileId.H2 -> 62
            TileId.H3 -> 61
            TileId.H4 -> 60
            TileId.H5 -> 59
            TileId.H6 -> 58
            TileId.H7 -> 57
            TileId.H8 -> 71
            TileId.H9 -> 70
            TileId.I1 -> 69
            TileId.I2 -> 68
            TileId.I3 -> 67
            TileId.I4 -> 66
            TileId.I5 -> 65
            TileId.I6 -> 64
            else -> -1
        }
    }
}
